server:
  port: 8083
  tomcat:
    uri-encoding: UTF-8   # 配置Tomcat编码,默认为UTF-8
    max-threads: 1000  # 配置最大线程数
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/webpage/  
      suffix: .jsp  
  thymeleaf: #关闭默认模板引擎
    cache: false
    enabled: false
  devtools:
    restart: #热部署生效
       enabled: true
       #additional-paths: src/main/java   #设置重启的目录
       #classpath   #目录下的WEB-INF文件夹内容修改不重启
       exclude: WEB-INF/**
  aop:
    auto: true
application:
  message: Hello BJ 
  
  